apiVersion: v1
kind: Service
metadata:
  name: hello-fsharp
  labels:
    app: hello-fsharp
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: hello-fsharp
    tier: frontend
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: frontend
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-fsharp
        tier: frontend
    spec:
      containers:
      - name: hello-fsharp
        image: gcr.io/kubernetes-logary/hello-fsharp:v2
        ports:
        - containerPort: 8080

